### ISSUE TITLE
Full path to trx2junit necessary in Circle CI

### ISSUE THREAD

**Issue by janaagaard75** [gfoidl/trx2junit#35]
This is not really a bug report, but more of an information: I had to write the full path to `trx2junit` (`/root/.dotnet/tools/trx2junit`) to get it to work in Circle CI.

Would it be worth mentioning this in the readme? It might also be nice to add a bit more info about configuring Circle CI. Here are the steps related to the tests in my `config.yml`.

```yaml
version: 2
jobs:
  build_and_deploy:
    docker:
      - image: microsoft/dotnet:2.2-sdk

      # ...

      - run:
          name: Run tests
          command: |
            dotnet test --logger trx --results-directory "..\TestResults"

      # ...

      - run:
          name: Install TRX 2 JUnit converter
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g trx2junit
          when: always

      - run:
          name: Convert TRX test results to JUnit format
          command: |
            /root/.dotnet/tools/trx2junit TestResults/*.trx
          when: always

      - store_test_results:
          path: TestResults
```
